version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    env_file:
      - .env
    hostname: redis

  postgres:
    image: postgres:15.2-bullseye
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    hostname: postgres

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
    command: go test -v -count=1 -tags=e2e ./tests/e2e/...

volumes:
  redis-data:
